### ISSUE TITLE
Web connector Service URL is not an a secure (https) server

### ISSUE THREAD

**Issue by RGKrish183** [RappidDevelopment/quickbooks-js#26]
Hi,

I have used your Quickbooks-Js to complete you development process, its working properly. But when try add my domain url in web connector i have getting error below,

> The application demo service URL is not on a secure (https) server. 
> QBWC1051: The new applicaiton was not added.

Ex. url below:
> http://domain.com:8000/wsdl?wsdl

I have put the SSL certificate also. But it will not allowing add my web connector.

And also i had doubt which you have given quickbooks-js npm is when creating server on http only, is there wants to any code change as https to create server.

Kindly help me get from this problem, i have spent almost 2 days for this issue.

**Comment by mattmorgis** [comment]
Hi @RGKrish183 

Can you verify that you have both:
1. properly setup and configured an SSL certificate that is not expired or self-signed 
2. can access your domain via `https` protocol?

**Comment by RGKrish183** [comment]
Hi,

Yes, i have done with **https web protocol**,.  now working fine. i have replace http to https when creating server in **lib/server.js** file.

> var https = require('https');
> var key = fs.readFileSync('encryption/privatekeyfile');
> var cert = fs.readFileSync( 'encryption/.bundlefile' );
> var ca = fs.readFileSync( 'encryption/intermediate.crtfile' );
> var options = { key: key, cert: cert,  ca: ca };
> https.createServer(options, app).listen(443);

And my current working url will be like below,

>https://domain.com:8000/wsdl?wsdl

Thanks @MattMorgis

**Comment by mattmorgis** [comment]
Hi @RGKrish183,

I think the issue here is with SSL and the port(s) you are listening on. 

I built this in a way [where the SOAP server runs and listens on HTTP,](https://github.com/RappidDevelopment/quickbooks-js/blob/master/lib/server.js#L93) port 8000 by default. I then use a [reverse proxy and SSL termination](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination) to forward requests to it. 

It appears you are telling the server to run on port `443`, while also specifying port `8000` in your URL. I would try commenting out [this line](https://github.com/RappidDevelopment/quickbooks-js/blob/master/lib/server.js#L93) and taking `8000` out of your URL.

It would be something like this:
```javascript
var https = require('https');
var key = fs.readFileSync('encryption/privatekeyfile');
var cert = fs.readFileSync( 'encryption/.bundlefile' );
var ca = fs.readFileSync( 'encryption/intermediate.crtfile' );
var options = { key: key, cert: cert, ca: ca };
https.createServer(options, app).listen(443);
soapServer = soap.listen(server, '/wsdl', this.webService.service, this.wsdl);
```

https://domain.com/wsdl
